import 'package:flutter/material.dart';

class AppColorScheme {
  static ColorScheme get lightScheme {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff8f4c35),
      surfaceTint: Color(0xff8f4c35),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffffdbd0),
      onPrimaryContainer: Color(0xff723520),
      secondary: Color(0xff77574d),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffffdbd0),
      onSecondaryContainer: Color(0xff5d4036),
      tertiary: Color(0xff6a5e2f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xfff3e2a7),
      onTertiaryContainer: Color(0xff51461a),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffff8f6),
      onSurface: Color(0xff231917),
      onSurfaceVariant: Color(0xff53433f),
      outline: Color(0xff85736e),
      outlineVariant: Color(0xffd8c2bb),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff392e2b),
      inversePrimary: Color(0xffffb59d),
      primaryFixed: Color(0xffffdbd0),
      onPrimaryFixed: Color(0xff390c00),
      primaryFixedDim: Color(0xffffb59d),
      onPrimaryFixedVariant: Color(0xff723520),
      secondaryFixed: Color(0xffffdbd0),
      onSecondaryFixed: Color(0xff2c160e),
      secondaryFixedDim: Color(0xffe7bdb0),
      onSecondaryFixedVariant: Color(0xff5d4036),
      tertiaryFixed: Color(0xfff3e2a7),
      onTertiaryFixed: Color(0xff221b00),
      tertiaryFixedDim: Color(0xffd6c68d),
      onTertiaryFixedVariant: Color(0xff51461a),
      surfaceDim: Color(0xffe8d6d1),
      surfaceBright: Color(0xfffff8f6),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff1ed),
      surfaceContainer: Color(0xfffceae5),
      surfaceContainerHigh: Color(0xfff7e4df),
      surfaceContainerHighest: Color(0xfff1dfda),
    );
  }

  static ColorScheme get darkScheme {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb59d),
      surfaceTint: Color(0xffffb59d),
      onPrimary: Color(0xff55200c),
      primaryContainer: Color(0xff723520),
      onPrimaryContainer: Color(0xffffdbd0),
      secondary: Color(0xffe7bdb0),
      onSecondary: Color(0xff442a21),
      secondaryContainer: Color(0xff5d4036),
      onSecondaryContainer: Color(0xffffdbd0),
      tertiary: Color(0xffd6c68d),
      onTertiary: Color(0xff393005),
      tertiaryContainer: Color(0xff51461a),
      onTertiaryContainer: Color(0xfff3e2a7),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff1a110f),
      onSurface: Color(0xfff1dfda),
      onSurfaceVariant: Color(0xffd8c2bb),
      outline: Color(0xffa08d87),
      outlineVariant: Color(0xff53433f),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xfff1dfda),
      inversePrimary: Color(0xff8f4c35),
      primaryFixed: Color(0xffffdbd0),
      onPrimaryFixed: Color(0xff390c00),
      primaryFixedDim: Color(0xffffb59d),
      onPrimaryFixedVariant: Color(0xff723520),
      secondaryFixed: Color(0xffffdbd0),
      onSecondaryFixed: Color(0xff2c160e),
      secondaryFixedDim: Color(0xffe7bdb0),
      onSecondaryFixedVariant: Color(0xff5d4036),
      tertiaryFixed: Color(0xfff3e2a7),
      onTertiaryFixed: Color(0xff221b00),
      tertiaryFixedDim: Color(0xffd6c68d),
      onTertiaryFixedVariant: Color(0xff51461a),
      surfaceDim: Color(0xff1a110f),
      surfaceBright: Color(0xff423733),
      surfaceContainerLowest: Color(0xff140c0a),
      surfaceContainerLow: Color(0xff231917),
      surfaceContainer: Color(0xff271d1a),
      surfaceContainerHigh: Color(0xff322825),
      surfaceContainerHighest: Color(0xff3d322f),
    );
  }
}
